### ISSUE TITLE
Setting minimum satellites in the UI

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav-configurator#1207]
Hey guys, just wondering if this is something we should look at removing?

![image](https://user-images.githubusercontent.com/17590174/112718259-b7f8eb80-8ee9-11eb-8367-3c37f26e48de.png)

It's something that should rarely be used. And people in the situation where they want to, can still set it in the CLI. I just see it as a temptation that could cause people who don't know what they're doing problems. Then I guess the same could be said for the whole position estimator block. However, the number of satellites for a lock, is something that is easier for people to understand; so some are tempted to play. They don't realise that below 5 3D locks the data starts getting bad.

Perhaps we could also move the entire position estimator block to the bottom of the page, just to keep it out of immediate sight.

I'm happy to do the work. I'm just looking for thoughts from you guys. @DzikuVx @digitalentity @avsaase Anyone else?

**Comment by avsaase** [comment]
I think these settings should stay. They are on a page with advanced settings and there is a big fat warning not to change them if you don't know what you're doing. I'm also not aware of any support questions caused by users changing these settings when they shouldn't. 

As for the min sats setting, the minimum value is 5 anyway. If people want to increase it a bit to get better home position accuracy there is no harm done in letting them.

**Comment by MrD-RC** [comment]
Sounds fair enough @avsaase. What do you think about moving the area to the bottom of the page?

**Comment by avsaase** [comment]
I think that makes sense.
