### ISSUE TITLE
NAV CRUISE box always highlighted

### ISSUE THREAD

**Issue by avsaase** [iNavFlight/inav-configurator#1279]
The NAV CRUISE box on the modes tab is always highlighted, even when the selected channel is not in the configured range. 

![2021-05-25 22_48_29-INAV Configurator](https://user-images.githubusercontent.com/880421/119621779-cf2f5900-be06-11eb-940d-755fc1066889.png)

**Comment by MrD-RC** [comment]
It is the same for Failsafe. It does not appear to be because of the re-ordering. I removed the re-ordering code and the false highlighting still existed. 

I also tested by removing every mode except for cruise and failsafe. Both would still light up, no matter what channel I put them on, or the range selected.

**Comment by Mateyhv** [comment]
Still there in RC2.

**Comment by OptimusTi** [comment]
Maybe 7045 fixes it?
