### ISSUE TITLE
Unable to build inav-configurator from source

### ISSUE THREAD

**Issue by laurin-1** [iNavFlight/inav-configurator#1324]
I'm unfortunately not able to build the configurator from source using the information provided by https://github.com/iNavFlight/inav-configurator/blob/master/README.md
The information seems to be outdated, the task release-only-linux isn't even defined in the gulpfile.js for example.
According to the documentation, npm install followed by npm run gulp release should be enough to build it, however when starting the built ./inav-configurator the result is the following:
![screenshot](https://user-images.githubusercontent.com/87230375/128783559-b465a2bc-64bc-483f-8fe0-bd6a725d260a.png)

I've tried different node versions(12.21.0,15.5.1(because it's mentioned in the window),16.6.1), the result is exactly the same with all of them. The ./inav-configurator is also a lot smaller than the precompiled one from Github, only approximately 220kB vs about 12MB. Both the release and the release-linux64 task lead to this, and it also doesn't matter how gulp is called or whether the included one or an already installed one is used.
I'm able to start the application using npm start, so I think there's either an issue with the gulpfile.js or the documentation omits an important step.

Two other things to mention:
Trying to use the release-linux64 task without prior usage of the task release results in an error(Error: ENOENT: no such file or directory, open 'apps/INAV-Configurator_linux64_3.0.1.tar.gz'), this can easily be replicated by deleting the apps folder and then trying to use the release-linux64 task.
The other thing is that the precompiled version of the configurator does not yet work with freshly compiled inav(3.1.0), the tag 3.0.1 has to be used in order to use self-built firmware with the released configurator.
![screenshot2](https://user-images.githubusercontent.com/87230375/128784644-155012f9-072b-4c38-ac9d-1fa9e35af5f7.png)

I'd appreciate it if someone could update the documentation and/or fix the gulpfile.js.

**Comment by alccrl** [comment]
HI,
I got same issue - Linux Ubuntu 20.04 LTS, last evening !
Build instructions are very "light".
Moreover ... I reached the same "nw.js" window only after copying dir *module-package* subdir (exact dirname may differ) from mwp-tools master dir (another tool for inav), and trying to rebuild  everything from npm install onwards.

There are many complaints on Internet about this tool chain (nw/nodejs/npm).

Alfredo

**Comment by alccrl** [comment]
Errata corrige:
same tool chain of configurator is used by blackbox explorer/viewer, not mwp-tools ...
 Sorry for the confusion ...

Alfredo

**Comment by alccrl** [comment]
Just an idea (not so expert in github) :
Has this behaviour to do with conflicting , one with the other, pending pull requests (e.g. #1166) ?
I included all pull requests in the source code set ..... before build.

May be someone more tunen on this repository may answer ...

Alfredo

**Comment by alccrl** [comment]
After :
rm package-lock.json
npm update
npm install
npm start
inav-configurator comes out ....
but
"gulp release" and other target flavours do not produce inav--configurator as expected, only "nw.js" app appears ...

Alfredo

**Comment by alccrl** [comment]
So,
I carried on today a few trials on linux-64 and I had a look at the console messages while building.
I used yarn (just to compare behaviour) together with npm, and I noticed that my "node" laptop installation was part "overwritten" by the just downloaded stuff from internet while following the readme.md instructions.

I succeded in building inav-configurator (elf) executable after resolving the windows icon missing problem.
Since I used the linux-64 task, I do not understand why the windows icon is necessary.

searchin the Internet I catched this URL:
https://askubuntu.com/questions/841847/mono-package-for-wine-is-not-installed :

What I found :
"Do the following to install wine-mono:

Download wine-mono.msi from the official WineHQ site.
Type wine64 uninstaller.
Press install from the uninstaller GUI and select the downloaded .msi package.
Done!"
it worked for me - (download same version as Your wine installation ...) and after this wine fix I was able to run gulp task again completely. : 

> gulp apps --linux64
[20:20:44] Using gulpfile ~/inav-configurator-master/gulpfile.js
[20:20:44] Starting 'apps'...
[20:20:44] Starting 'dist'...
[20:20:44] Starting 'clean'...
[20:20:45] Finished 'clean' after 398 ms
[20:20:45] Starting 'dist-build'...
[20:20:45] Starting 'build'...
[20:20:45] Starting 'build-all-css'...
[20:20:45] Starting 'build-all-js'...
[20:20:45] Starting 'build-css'...
[20:20:45] Starting 'build-receiver-css'...
[20:20:45] Starting 'build-js'...
[20:20:45] Starting 'build-receiver-js'...
[20:20:45] Starting 'build-debug-trace-js'...
[20:20:45] Starting 'build-hex-parser-js'...
[20:20:45] Finished 'build-debug-trace-js' after 161 ms
[20:20:45] Finished 'build-hex-parser-js' after 162 ms
[20:20:45] Finished 'build-receiver-css' after 175 ms
[20:20:45] Finished 'build-receiver-js' after 201 ms
[20:20:45] Finished 'build-css' after 225 ms
[20:20:45] Finished 'build-all-css' after 226 ms
[20:20:45] Finished 'build-js' after 361 ms
[20:20:45] Finished 'build-all-js' after 362 ms
[20:20:45] Finished 'build' after 362 ms
[20:20:45] Starting '<anonymous>'...
[20:20:46] Finished '<anonymous>' after 777 ms
[20:20:46] Finished 'dist-build' after 1.14 s
[20:20:46] Finished 'dist' after 1.54 s
[20:20:46] Starting '<anonymous>'...
Using v0.50.3 (normal)
Create cache folder in /home/alfredo/inav-configurator-master/cache/0.50.3-normal
Using cache for: win32
Create cache folder in /home/alfredo/inav-configurator-master/cache/0.50.3-normal
Using cache for: win64
Create cache folder in /home/alfredo/inav-configurator-master/cache/0.50.3-normal
Using cache for: osx64
Create cache folder in /home/alfredo/inav-configurator-master/cache/0.50.3-normal
Using cache for: linux32
Create cache folder in /home/alfredo/inav-configurator-master/cache/0.50.3-normal
Using cache for: linux64
Create release folder in /home/alfredo/inav-configurator-master/apps/inav-configurator/win64
Create release folder in /home/alfredo/inav-configurator-master/apps/inav-configurator/win32
Create release folder in /home/alfredo/inav-configurator-master/apps/inav-configurator/linux32
Create release folder in /home/alfredo/inav-configurator-master/apps/inav-configurator/linux64
Create release folder in /home/alfredo/inav-configurator-master/apps/inav-configurator/osx64
Update win64 executable icon
Update win32 executable icon
Zipping _locales/en/messages.json
Zipping build/debug-trace.js
Zipping build/hex_parser.js
Zipping build/receiver-msp.css
Zipping build/receiver-msp.js
Zipping build/script.js
Zipping build/styles.css
Zipping eventPage.js
Zipping images/arrow.svg
Zipping images/arrows.png
Zipping images/btn-donate.png
Zipping images/btn-patreon.png
Zipping images/btn-paypal.png
Zipping images/btn-yandex.png
Zipping images/CF_settings_black.svg
Zipping images/cf_logo_white.svg
Zipping images/CF_settings_white.svg
Zipping images/CF_settings_white.png
Zipping images/CF_template_white.svg
Zipping images/flightindicators/altitude_pressure.svg
Zipping images/flightindicators/altitude_ticks.svg
Zipping images/flightindicators/fi_box.svg
Zipping images/flightindicators/fi_circle.svg
Zipping images/flightindicators/fi_needle_small.svg
Zipping images/flightindicators/fi_needle.svg
Zipping images/flightindicators/fi_tc_airplane.svg
Zipping images/flightindicators/heading_mechanics.svg
Zipping images/flightindicators/heading_yaw.svg
Zipping images/flightindicators/horizon_back.svg
Zipping images/flightindicators/horizon_ball.svg
Zipping images/flightindicators/horizon_circle.svg
Zipping images/flightindicators/horizon_mechanics.svg
Zipping images/flightindicators/speed_mechanics.svg
Zipping images/flightindicators/turn_coordinator.svg
Zipping images/flightindicators/vertical_mechanics.svg
Zipping images/icons/cf_failsafe_procedure1.svg
Zipping images/icons/cf_failsafe_procedure2.svg
Zipping images/icons/cf_failsafe_procedure3.svg
Zipping images/icons/cf_failsafe_procedure4.svg
Zipping images/icons/cf_icon_adjust_grey.svg
Zipping images/icons/cf_icon_adjust_white.svg
Zipping images/icons/cf_icon_advanced_white.svg
Zipping images/icons/cf_icon_advanced_grey.svg
Zipping images/icons/cf_icon_armed_active.svg
Zipping images/icons/cf_icon_armed_grey.svg
Zipping images/icons/cf_icon_arrow.png
Zipping images/icons/cf_icon_arrow.svg
Zipping images/icons/cf_icon_backup_grey.svg
Zipping images/icons/cf_icon_backup_white.svg
Zipping images/icons/cf_icon_bat_grey.svg
Zipping images/icons/cf_icon_cal_grey.svg
Zipping images/icons/cf_icon_cal_white.svg
Zipping images/icons/cf_icon_cli_grey.svg
Zipping images/icons/cf_icon_cli_white.svg
Zipping images/icons/cf_icon_config_grey.svg
Zipping images/icons/cf_icon_config_white.svg
Zipping images/icons/cf_icon_data_grey.svg
Zipping images/icons/cf_icon_data_white.svg
Zipping images/icons/cf_icon_elevation_white.svg
Zipping images/icons/cf_icon_failsafe_active.svg
Zipping images/icons/cf_icon_failsafe_grey.svg
Zipping images/icons/cf_icon_failsafe_white.svg
Zipping images/icons/cf_icon_filter.svg
Zipping images/icons/cf_icon_flasher_grey.svg
Zipping images/icons/cf_icon_flasher_white.svg
Zipping images/icons/cf_icon_gps_grey.svg
Zipping images/icons/cf_icon_gps_white.svg
Zipping images/icons/cf_icon_help_grey.svg
Zipping images/icons/cf_icon_help_white.svg
Zipping images/icons/cf_icon_home.png
Zipping images/icons/cf_icon_info_green.svg
Zipping images/icons/cf_icon_info_grey.svg
Zipping images/icons/cf_icon_led_grey.svg
Zipping images/icons/cf_icon_led_white.svg
Zipping images/icons/cf_icon_link_active.svg
Zipping images/icons/cf_icon_link_grey.svg
Zipping images/icons/cf_icon_log_grey.svg
Zipping images/icons/cf_icon_log_white.svg
Zipping images/icons/cf_icon_mission_grey.svg
Zipping images/icons/cf_icon_mission_white.svg
Zipping images/icons/cf_icon_mixer_grey.svg
Zipping images/icons/cf_icon_mixer_white.svg
Zipping images/icons/cf_icon_modes_grey.svg
Zipping images/icons/cf_icon_modes_white.svg
Zipping images/icons/cf_icon_motor_grey.svg
Zipping images/icons/cf_icon_motor_white.svg
Zipping images/icons/cf_icon_MP_add_grey.svg
Zipping images/icons/cf_icon_MP_cancel_grey.svg
Zipping images/icons/cf_icon_MP_center_grey.svg
Zipping images/icons/cf_icon_MP_hide_grey.svg
Zipping images/icons/cf_icon_MP_loadFile_grey.svg
Zipping images/icons/cf_icon_MP_loadFromEprom_grey.svg
Zipping images/icons/cf_icon_MP_loadFromFC_grey.svg
Zipping images/icons/cf_icon_MP_play_grey.svg
Zipping images/icons/cf_icon_MP_reduce_grey.svg
Zipping images/icons/cf_icon_MP_removeAll_grey.svg
Zipping images/icons/cf_icon_MP_safehome_green.svg
Zipping images/icons/cf_icon_MP_safehome_grey.svg
Zipping images/icons/cf_icon_MP_safehome_red.svg
Zipping images/icons/cf_icon_MP_safehome_white.svg
Zipping images/icons/cf_icon_MP_save_grey.svg
Zipping images/icons/cf_icon_MP_save2Eprom_grey.svg
Zipping images/icons/cf_icon_MP_save2FC_grey.svg
Zipping images/icons/cf_icon_MP_save2FC.svg
Zipping images/icons/cf_icon_MP_saveFile_grey.svg
Zipping images/icons/cf_icon_MP_show_grey.svg
Zipping images/icons/cf_icon_MP_stop_grey.svg
Zipping images/icons/cf_icon_pid_grey.svg
Zipping images/icons/cf_icon_pid_white.svg
Zipping images/icons/cf_icon_pitch.svg
Zipping images/icons/cf_icon_ports_grey.svg
Zipping images/icons/cf_icon_ports_white.svg
Zipping images/icons/cf_icon_position_edit.png
Zipping images/icons/cf_icon_position_head.png
Zipping images/icons/cf_icon_position_LDG_edit.png
Zipping images/icons/cf_icon_position_LDG.png
Zipping images/icons/cf_icon_position_PH_edit.png
Zipping images/icons/cf_icon_position_PH.png
Zipping images/icons/cf_icon_position_POI_edit.png
Zipping images/icons/cf_icon_position_POI.png
Zipping images/icons/cf_icon_position_WP_edit.png
Zipping images/icons/cf_icon_position_WP.png
Zipping images/icons/cf_icon_position.png
Zipping images/icons/cf_icon_position.svg
Zipping images/icons/cf_icon_quad.svg
Zipping images/icons/cf_icon_roll.svg
Zipping images/icons/cf_icon_RTH.png
Zipping images/icons/cf_icon_rx_grey.svg
Zipping images/icons/cf_icon_rx_white.svg
Zipping images/icons/cf_icon_safehome_used.png
Zipping images/icons/cf_icon_safehome_white.svg
Zipping images/icons/cf_icon_safehome.png
Zipping images/icons/cf_icon_sdcard.svg
Zipping images/icons/cf_icon_sensors_grey.svg
Zipping images/icons/cf_icon_sensors_white.svg
Zipping images/icons/cf_icon_servo_grey.svg
Zipping images/icons/cf_icon_servo_white.svg
Zipping images/icons/cf_icon_settings_white.svg
Zipping images/icons/cf_icon_setup_grey.svg
Zipping images/icons/cf_icon_setup_white.svg
Zipping images/icons/cf_icon_transponder_grey.svg
Zipping images/icons/cf_icon_transponder_white.svg
Zipping images/icons/cf_icon_usb1_white.svg
Zipping images/icons/cf_icon_usb2_white.svg
Zipping images/icons/cf_icon_welcome_grey.svg
Zipping images/icons/cf_icon_welcome_white.svg
Zipping images/icons/cf_icon_wizard_grey.svg
Zipping images/icons/cf_icon_wizard_white.svg
Zipping images/icons/cf_icon_yaw.svg
Zipping images/icons/check.svg
Zipping images/icons/close1.svg
Zipping images/icons/cross2.svg
Zipping images/icons/icon_mission_airplane.png
Zipping images/icons/icon_osd_white.svg
Zipping images/icons/icon_osd.svg
Zipping images/icons/nopass.svg
Zipping images/icons/pass.svg
Zipping images/icons/peset_default.svg
Zipping images/icons/peset_plane.svg
Zipping images/icons/peset_quad.svg
Zipping images/icons/peset_wing.svg
Zipping images/icons/pos1_grey.svg
Zipping images/icons/pos1.svg
Zipping images/icons/pos2_grey.svg
Zipping images/icons/pos2.svg
Zipping images/icons/pos3_grey.svg
Zipping images/icons/pos3.svg
Zipping images/icons/pos4_grey.svg
Zipping images/icons/pos4.svg
Zipping images/icons/pos5_grey.svg
Zipping images/icons/pos5.svg
Zipping images/icons/pos6_grey.svg
Zipping images/icons/pos6.svg
Zipping images/icons/scroll.svg
Zipping images/icons/sensor_acc_error.png
Zipping images/icons/sensor_acc_off.png
Zipping images/icons/sensor_acc_on.png
Zipping images/icons/sensor_airspeed_.psd
Zipping images/icons/sensor_airspeed_error.png
Zipping images/icons/sensor_airspeed_on.png
Zipping images/icons/sensor_airspeed_off.png
Zipping images/icons/sensor_baro_error.png
Zipping images/icons/sensor_baro_off.png
Zipping images/icons/sensor_baro_on.png
Zipping images/icons/sensor_flow_.psd
Zipping images/icons/sensor_flow_error.png
Zipping images/icons/sensor_flow_off.png
Zipping images/icons/sensor_flow_on.png
Zipping images/icons/sensor_gyro_error.png
Zipping images/icons/sensor_gyro_off.png
Zipping images/icons/sensor_gyro_on.png
Zipping images/icons/sensor_imu2_error.png
Zipping images/icons/sensor_imu2_off.png
Zipping images/icons/sensor_imu2_on.png
Zipping images/icons/sensor_mag_error.png
Zipping images/icons/sensor_mag_off.png
Zipping images/icons/sensor_mag_on.png
Zipping images/icons/sensor_sat_error.png
Zipping images/icons/sensor_sat_off.png
Zipping images/icons/sensor_sat_on.png
Zipping images/icons/sensor_sonar_error.png
Zipping images/icons/sensor_sonar_off.png
Zipping images/icons/sensor_sonar_on.png
Zipping images/inav_icon_128.png
Zipping images/inav_icon_128.psd
Zipping images/inav.icns
Zipping images/inav.ico
Zipping images/light-wide-1.svg
Zipping images/light-wide-2.svg
Zipping images/loading-bars.svg
Zipping images/loading-spin.svg
Zipping images/map_bg.svg
Zipping images/osd-bg-1.jpg
Zipping images/paper.jpg
Zipping images/partner/adpm.png
Zipping images/partner/airbot.png
Zipping images/partner/carbonbird.png
Zipping images/partner/mateksys.png
Zipping main.html
Zipping manifest.json
Zipping package.json
Zipping resources/models/fallback.json
Zipping resources/models/fallback.png
Zipping resources/models/flying_wing.json
Zipping resources/models/hex_plus.json
Zipping resources/models/hex_x.json
Zipping resources/models/quad_atail.json
Zipping resources/models/quad_vtail.json
Zipping resources/models/quad_x.json
Zipping resources/models/rudderless_plane.json
Zipping resources/models/tricopter.json
Zipping resources/models/twin_plane.json
Zipping resources/models/vtail_plane.json
Zipping resources/models/vtail_single_servo_plane.json
Zipping resources/models/y4.json
Zipping resources/models/y6.json
Zipping resources/motor_order/airplane_norudder.svg
Zipping resources/motor_order/airplane_vtail_single.svg
Zipping resources/motor_order/airplane_vtail.svg
Zipping resources/motor_order/airplane.svg
Zipping resources/motor_order/atail_quad.svg
Zipping resources/motor_order/bicopter.svg
Zipping resources/motor_order/custom.svg
Zipping resources/motor_order/flying_wing.svg
Zipping resources/motor_order/hex_p.svg
Zipping resources/motor_order/hex_x.svg
Zipping resources/motor_order/octo_flat_p.svg
Zipping resources/motor_order/octo_flat_x.svg
Zipping resources/motor_order/octo_x8.svg
Zipping resources/motor_order/quad_p.svg
Zipping resources/motor_order/quad_x.svg
Zipping resources/motor_order/tri.svg
Zipping resources/motor_order/vtail_quad.svg
Zipping resources/motor_order/y4.svg
Zipping resources/motor_order/y6.svg
Zipping resources/osd/bold.mcm
Zipping resources/osd/clarity_medium.mcm
Zipping resources/osd/clarity.mcm
Zipping resources/osd/default.mcm
Zipping resources/osd/impact_mini.mcm
Zipping resources/osd/impact.mcm
Zipping resources/osd/large.mcm
Zipping resources/osd/vision.mcm
Zipping src/css/font-awesome/fonts/fontawesome-webfont.eot
Zipping src/css/font-awesome/fonts/fontawesome-webfont.svg
Zipping src/css/font-awesome/fonts/fontawesome-webfont.ttf
Zipping src/css/font-awesome/fonts/fontawesome-webfont.woff
Zipping src/css/font-awesome/fonts/fontawesome-webfont.woff2
Zipping src/css/font-awesome/fonts/FontAwesome.otf
Zipping src/css/opensans_webfontkit/opensans-bold-webfont.eot
Zipping src/css/opensans_webfontkit/opensans-bold-webfont.svg
Zipping src/css/opensans_webfontkit/opensans-bold-webfont.ttf
Zipping src/css/opensans_webfontkit/opensans-bold-webfont.woff
Zipping src/css/opensans_webfontkit/opensans-bold-webfont.woff2
Zipping src/css/opensans_webfontkit/opensans-bolditalic-webfont.eot
Zipping src/css/opensans_webfontkit/opensans-bolditalic-webfont.svg
Zipping src/css/opensans_webfontkit/opensans-bolditalic-webfont.ttf
Zipping src/css/opensans_webfontkit/opensans-bolditalic-webfont.woff
Zipping src/css/opensans_webfontkit/opensans-bolditalic-webfont.woff2
Zipping src/css/opensans_webfontkit/opensans-italic-webfont.eot
Zipping src/css/opensans_webfontkit/opensans-italic-webfont.svg
Zipping src/css/opensans_webfontkit/opensans-italic-webfont.ttf
Zipping src/css/opensans_webfontkit/opensans-italic-webfont.woff
Zipping src/css/opensans_webfontkit/opensans-italic-webfont.woff2
Zipping src/css/opensans_webfontkit/opensans-light-webfont.eot
Zipping src/css/opensans_webfontkit/opensans-light-webfont.svg
Zipping src/css/opensans_webfontkit/opensans-light-webfont.ttf
Zipping src/css/opensans_webfontkit/opensans-light-webfont.woff
Zipping src/css/opensans_webfontkit/opensans-light-webfont.woff2
Zipping src/css/opensans_webfontkit/opensans-regular-webfont.eot
Zipping src/css/opensans_webfontkit/opensans-regular-webfont.svg
Zipping src/css/opensans_webfontkit/opensans-regular-webfont.ttf
Zipping src/css/opensans_webfontkit/opensans-regular-webfont.woff
Zipping src/css/opensans_webfontkit/opensans-regular-webfont.woff2
Zipping src/css/opensans_webfontkit/opensans-semibold-webfont.eot
Zipping src/css/opensans_webfontkit/opensans-semibold-webfont.svg
Zipping src/css/opensans_webfontkit/opensans-semibold-webfont.ttf
Zipping src/css/opensans_webfontkit/opensans-semibold-webfont.woff
Zipping src/css/opensans_webfontkit/opensans-semibold-webfont.woff2
Zipping tabs/adjustments.html
Zipping tabs/advanced_tuning.html
Zipping tabs/auxiliary.html
Zipping tabs/blank.html
Zipping tabs/calibration.html
Zipping tabs/cli.html
Zipping tabs/configuration.html
Zipping tabs/debug_trace.html
Zipping tabs/failsafe.html
Zipping tabs/firmware_flasher.html
Zipping tabs/gps.html
Zipping tabs/landing.html
Zipping tabs/led_strip.html
Zipping tabs/logging.html
Zipping tabs/mission_control.html
Zipping tabs/mixer.html
Zipping tabs/modes.html
Zipping tabs/onboard_logging.html
Zipping tabs/options.html
Zipping tabs/osd.html
Zipping tabs/outputs.html
Zipping tabs/pid_tuning.html
Zipping tabs/ports.html
Zipping tabs/programming.html
Zipping tabs/receiver_msp.html
Zipping tabs/receiver.html
Zipping tabs/review.html
Zipping tabs/sensors.html
Zipping tabs/setup.html
Zipping tabs/transponder.html
[20:21:02] Finished '<anonymous>' after 16 s
[20:21:02] Finished 'apps' after 18 s

The inav-configurator executable (elf) obtained is about 14 Mbyte and works, at least on my development laptop !!!.

My impression is that a completely automated configurator build chain implies continous checks against platform tools updates and changes, and this is a very hard task to accomplish, but to add more descritpions and cases to the readme.md should be a more affordable and simple task.
As soon as I will install a fresh linux box somewhere, I will try to run the configurator on it, because my laptop is too crowded with development tools, so it does not represent a typical installation scenario.
I also will try to build under Windows. I did not yet succed... (I yet had not enough time to investigate why).

Conclusion (for now):
Somewhere in the building/execution process there is a point where errors are not reported and nw.js appears, instead of the complete configurator.

Hope this helps ...

Alfredo

**Comment by laurin-1** [comment]
Amazing! Great find! Very helpful indeed, Alfredo!
I was able to successfully run npm run gulp release after installing wine-mono from https://dl.winehq.org/wine/wine-mono/ .
![image](https://user-images.githubusercontent.com/87230375/130533201-747a3c1c-2784-4834-bf14-7e114c9a916d.png)

The readme only mentions that wine needs to be installed, not that wine-mono is required.
The release-linux64 task seems to be partially broken, it can't be run when the release task wasn't already run prior, the resulting error message is:
`> inav-configurator@3.0.1 gulp
> gulp "release-linux64"

[01:26:11] Using gulpfile ~/Git/inav-configurator/gulpfile.js
[01:26:11] Starting 'release-linux64'...
[01:26:12] Finished 'release-linux64' after 12 ms
node:events:371
      throw er; // Unhandled 'error' event
      ^

<ref *1> Error: ENOENT: no such file or directory, open 'apps/INAV-Configurator_linux64_3.0.1.tar.gz'
Emitted 'error' event on Domain instance at:
    at WriteStream.emit (node:domain:525:12)
    at WriteStream.onerror (/home/laurin/Git/inav-configurator/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at WriteStream.emit (node:events:394:28)
    at WriteStream.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'apps/INAV-Configurator_linux64_3.0.1.tar.gz',
  domainEmitter: WriteStream {
    path: 'apps/INAV-Configurator_linux64_3.0.1.tar.gz',
    flags: 'w',
    mode: 438,
    fd: null,
    start: undefined,
    pos: undefined,
    bytesWritten: 0,
    closed: false,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: true,
      emitClose: true,
      autoDestroy: true,
      errored: [Circular *1],
      closed: true,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      [Symbol(kConstruct)]: [Function: bound onceWrapper] { listener: [Function (anonymous)] }
    },
    _eventsCount: 1,
    _maxListeners: undefined,
    emit: [Function: emit],
    [Symbol(kFs)]: {
      appendFile: [Function: appendFile],
      appendFileSync: [Function: appendFileSync],
      access: [Function: access],
      accessSync: [Function: accessSync],
      chown: [Function: chown],
      chownSync: [Function: chownSync],
      chmod: [Function: chmod],
      chmodSync: [Function: chmodSync],
      close: [Function (anonymous)],
      closeSync: [Function (anonymous)],
      copyFile: [Function: copyFile],
      copyFileSync: [Function: copyFileSync],
      createReadStream: [Function: createReadStream],
      createWriteStream: [Function: createWriteStream],
      exists: [Function: exists],
      existsSync: [Function: existsSync],
      fchown: [Function: fchown],
      fchownSync: [Function: fchownSync],
      fchmod: [Function: fchmod],
      fchmodSync: [Function: fchmodSync],
      fdatasync: [Function: fdatasync],
      fdatasyncSync: [Function: fdatasyncSync],
      fstat: [Function: fstat],
      fstatSync: [Function: fstatSync],
      fsync: [Function: fsync],
      fsyncSync: [Function: fsyncSync],
      ftruncate: [Function: ftruncate],
      ftruncateSync: [Function: ftruncateSync],
      futimes: [Function: futimes],
      futimesSync: [Function: futimesSync],
      lchown: [Function: lchown],
      lchownSync: [Function: lchownSync],
      lchmod: undefined,
      lchmodSync: undefined,
      link: [Function: link],
      linkSync: [Function: linkSync],
      lstat: [Function: lstat],
      lstatSync: [Function: lstatSync],
      lutimes: [Function: lutimes],
      lutimesSync: [Function: lutimesSync],
      mkdir: [Function: mkdir],
      mkdirSync: [Function: mkdirSync],
      mkdtemp: [Function: mkdtemp],
      mkdtempSync: [Function: mkdtempSync],
      open: [Function: open],
      openSync: [Function: openSync],
      opendir: [Function: opendir],
      opendirSync: [Function: opendirSync],
      readdir: [Function: readdir],
      readdirSync: [Function: readdirSync],
      read: [Function: read],
      readSync: [Function: readSync],
      readv: [Function: readv],
      readvSync: [Function: readvSync],
      readFile: [Function: readFile],
      readFileSync: [Function: readFileSync],
      readlink: [Function: readlink],
      readlinkSync: [Function: readlinkSync],
      realpath: [Function: realpath] { native: [Function (anonymous)] },
      realpathSync: [Function: realpathSync] { native: [Function (anonymous)] },
      rename: [Function: rename],
      renameSync: [Function: renameSync],
      rm: [Function: rm],
      rmSync: [Function: rmSync],
      rmdir: [Function: rmdir],
      rmdirSync: [Function: rmdirSync],
      stat: [Function: stat],
      statSync: [Function: statSync],
      symlink: [Function: symlink],
      symlinkSync: [Function: symlinkSync],
      truncate: [Function: truncate],
      truncateSync: [Function: truncateSync],
      unwatchFile: [Function: unwatchFile],
      unlink: [Function: unlink],
      unlinkSync: [Function: unlinkSync],
      utimes: [Function: utimes],
      utimesSync: [Function: utimesSync],
      watch: [Function: watch],
      watchFile: [Function: watchFile],
      writeFile: [Function: writeFile],
      writeFileSync: [Function: writeFileSync],
      write: [Function: write],
      writeSync: [Function: writeSync],
      writev: [Function: writev],
      writevSync: [Function: writevSync],
      Dir: [class Dir],
      Dirent: [class Dirent],
      Stats: [Function: Stats],
      ReadStream: [Getter/Setter],
      WriteStream: [Getter/Setter],
      FileReadStream: [Getter/Setter],
      FileWriteStream: [Getter/Setter],
      _toUnixTimestamp: [Function: toUnixTimestamp],
      F_OK: 0,
      R_OK: 4,
      W_OK: 2,
      X_OK: 1,
      constants: [Object: null prototype] {
        UV_FS_SYMLINK_DIR: 1,
        UV_FS_SYMLINK_JUNCTION: 2,
        O_RDONLY: 0,
        O_WRONLY: 1,
        O_RDWR: 2,
        UV_DIRENT_UNKNOWN: 0,
        UV_DIRENT_FILE: 1,
        UV_DIRENT_DIR: 2,
        UV_DIRENT_LINK: 3,
        UV_DIRENT_FIFO: 4,
        UV_DIRENT_SOCKET: 5,
        UV_DIRENT_CHAR: 6,
        UV_DIRENT_BLOCK: 7,
        S_IFMT: 61440,
        S_IFREG: 32768,
        S_IFDIR: 16384,
        S_IFCHR: 8192,
        S_IFBLK: 24576,
        S_IFIFO: 4096,
        S_IFLNK: 40960,
        S_IFSOCK: 49152,
        O_CREAT: 64,
        O_EXCL: 128,
        UV_FS_O_FILEMAP: 0,
        O_NOCTTY: 256,
        O_TRUNC: 512,
        O_APPEND: 1024,
        O_DIRECTORY: 65536,
        O_NOATIME: 262144,
        O_NOFOLLOW: 131072,
        O_SYNC: 1052672,
        O_DSYNC: 4096,
        O_DIRECT: 16384,
        O_NONBLOCK: 2048,
        S_IRWXU: 448,
        S_IRUSR: 256,
        S_IWUSR: 128,
        S_IXUSR: 64,
        S_IRWXG: 56,
        S_IRGRP: 32,
        S_IWGRP: 16,
        S_IXGRP: 8,
        S_IRWXO: 7,
        S_IROTH: 4,
        S_IWOTH: 2,
        S_IXOTH: 1,
        F_OK: 0,
        R_OK: 4,
        W_OK: 2,
        X_OK: 1,
        UV_FS_COPYFILE_EXCL: 1,
        COPYFILE_EXCL: 1,
        UV_FS_COPYFILE_FICLONE: 2,
        COPYFILE_FICLONE: 2,
        UV_FS_COPYFILE_FICLONE_FORCE: 4,
        COPYFILE_FICLONE_FORCE: 4
      },
      promises: [Getter]
    },
    [Symbol(kIsPerformingIO)]: false,
    [Symbol(kCapture)]: false
  },
  domainThrown: false
}`

And even after the release task was run, it doesn't seem to work correctly, it only seems to generate a fraction of the files the release task generates.
So, as long as the release-linux64 task is not fixed, the installation of wine-mono is required, since only the release task seems to work correctly.
Therefore, like Alfredo already concluded, the most viable short term solution is to update the readme.

**Comment by alccrl** [comment]
Thanks for testing !

I also just succeded in building under Win10, but before I had to delete mac_os and linux tasks form gulpfile, there was an exception about symbolic links during (not avoidable (?)) execution of mac_os task.
Leaving only win64 task in gulpfile, "gulp apps" task does complete and generates a zip file with inav-configurator exe file (16 mbyte).

Alfredo
