### ISSUE TITLE
Inspect no longer accessible in Configurator 

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav-configurator#1469]
Right clicking in Configurator when using npm start no longer give a menu of Chrome browser commands, including **Inspect**. This seems to be since updating the nw,js version. The feature was working fine before it updated earlier today.

Anyway to get this back? It's very helpful for development.

**Comment by DzikuVx** [comment]
You could have just asked :) 
`npm install nw@0.61.0 --nwjs_build_type=sdk`

**Comment by MrD-RC** [comment]
Thought it may have been a bug as it was always on by default before. I’ll update my install script. Thanks Pawel.

**Comment by breadoven** [comment]
OK what's the trick to getting this to work ? Tried installing the SDK version (61 and the latest 67.1) but can't get the Inspector/Console to appear using F12 or anything else. Pretty difficult to debug without this.

**Comment by DzikuVx** [comment]
@breadoven 

```
rm -rf ./node_modules/nw/*
npm install nw@0.61.0 --nwjs_build_type=sdk
```

**Comment by breadoven** [comment]
Well tried the above and Configurator wouldn't run at all afterwards (some problem with openlayers). So deleted the node_modules folder and ran `npm install nw@0.61.0 --nwjs_build_type=sdk` which fixed Configurator running ... but still no Inspector using F12/Cntl Shift J ?. 

However, `npm view nw version` returns `0.67.1` rather than the `0.67.1-sdk` I'd have expected so it doesn't appear to have installed the SDK version for some reason. Not sure what the problem is.

**Comment by breadoven** [comment]
OK just tried `npm install nw@0.61.0-sdk` and bizarrely that worked, Inspector now appears. Don't know if this means `--nwjs_build_type=sdk` is broken or something just randomly screwed up.
