### ISSUE TITLE
Big differences in height between Bing Maps and Google Maps

### ISSUE THREAD

**Issue by cptX** [iNavFlight/inav-configurator#1909]
Hi, I have recently succeeded in making my airplane flying autonomously following waypoints and now I want to start flying to longer paths so the relative reference of the height compared to the take off height makes less sense here. I want to start using an absolute height measurement method, but I have noticed significant differences in height between google earth and bing embedded in inav.
For example if you go to the coordinates 37.9844368, 23.866687 inav configurator gives 209m height (Sea level DEM Model disabled), and Google earth gives 168m. It's a 41m difference!!! I don't know what height to trust.
Also, I have tested enabling the "Use Sea Level Earth DEM Model" for several positions in Greece and in some places it is worse than disabled and in some better that disabled. In our specific location by enabling this I get 170m which is very close to Google Earth's value. Testing the same functionality in the mountains of Crete I saw worse results when enabling this option.
I have started studying the different systems of height models and have understood that the GPS module on the aircraft actually uses wgs84 with ellipsoid system, so this tells me that it's better to keep the option "Use Sea Level Earth DEM Model" disabled as this will use the sea-level instead of the ellipsoid and will result to greater differences.
So the data I have at the moment are quite contradictory and height differences of 40m will create greate problems ...
I'll measure the height using the gps in my mobile phone next time in order to have this info available too. I have done this to other places and it has differences with both bing and google making the problem even worse.
How do you cope with these issues, what can we do to have a better preditiction of the terrain height?
Also, the altitute during flight is based on gps or both gps and barometer? I mean could be that I have set the correct heights according to the map but because barometer gives completely different values the aircraft will fly to a different altitude than the one given by the gps module making the whole altitude prediction useless?

**Comment by MrD-RC** [comment]
It really isn’t different. That issue raised the exact same problem. Which has been looked at and fixed. The resulting PR should end the massive discrepancies in altitude. 

From everywhere we tested Bing maps, when used in Mission Control, was out by 20 to 50 metres. That actually answers your question on which is more accurate; the answer being not Bing. We tested different locations using different map providers and taking measurements at the locations with GPS; before Marc submitted that issue. 

This problem was tracked to Bing using the Ellipsoid method instead of sea level. Which generally is more accurate. However the only way to be 100% certain is to measure the MSL altitude yourself. Also be aware that INAV doesn’t use Google maps. The alternative is OpenStreetMaps. Which was similar in altitude to Google and other providers. Usually within a metre. Worst case 5 metres difference.
