### ISSUE TITLE
Instruments window

### ISSUE THREAD

**Issue by Xe54** [iNavFlight/inav-configurator#208]
Hi guys,
i'm missing the instruments display window in the setup tab. Is there a reason why it'not there any more? Mag display was very useful if you want to find out which way your hardware magnetometer is mounted on the board in GPS module. Is it possible to enable instumets again?

**Comment by DzikuVx** [comment]
Those instruments will rather not come back since due their size they were pretty useless. To align magnetometer please use Heading in model windows.
There is a plan to add a "Instruments" tab to allow BLOS operations but this is future

![image](https://user-images.githubusercontent.com/966811/27097950-2c6494bc-5076-11e7-93ce-f3fe802e8c68.png)
