### ISSUE TITLE
[master] Mission Control tab crashes when WP altitude value is adjusted

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav-configurator#2135]
When attempting to plot a WP mission, and you proceed to alter the altitude of the way point marker. The tab crashes.

![mission](https://github.com/iNavFlight/inav-configurator/assets/47995726/33459379-f730-407d-8f12-c39d32b14073)

Latest build using Windows OS.. Cache was cleared.

**Comment by breadoven** [comment]
I get the same thing when not running in debug mode. In debug mode there's no crash but there are errors:
"Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')"

It's related to the conversion of cm to m in the text after the altitude input box. Not sure what the problem is though since it seems to convert to meters correctly even with the errors.
