### ISSUE TITLE
Configurator 1.9.3 issue with Windows 7 x64

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#409]
Reported in YouTube comments:

> Downloaded the 1.9.3 configurator and it will not open on my 64 bit win 7 laptop. Get a message saying ""Your profile can not be used because it is from a newer version of NW.js. Some features may be unavailable. Please specify a different profile directory or use a newer version of NW.js. google nw.js and it reveals its some kind of trojan virus. now none of the versions of iav config will run on this laptop. Advice please.

**Comment by Lord-Quake** [comment]
I am running 1.9.3 on Windows 7 Home Premium SP 1 without any issues that I'm aware of.

**Comment by MRC3742** [comment]
I have gotten this same error running Windows7 x86 (32 bit)

It happens when trying to run an earlier stand alone version of configurator which was built with an earlier version of NW.js. The error image attached below.
![nw js01](https://user-images.githubusercontent.com/26642502/39503838-fe6308b4-4d95-11e8-9e2f-9979ba1826be.jpg)



When you run configurator it stores the version of NW.js somewhere in the user profile. When i do a custom build of configurator it always downloads the latest version of NW.js before it proceeds to build the release. So as newer versions of configurator are released older versions will throw this error.

Fix-WorkAround?
If I delete all the User Profile files located at C:\Users\{UserName}\AppData\Local\inav-configurator
then Restart configurator and it will rebuild this folder with no more errors.

**Comment by DzikuVx** [comment]
Since this is "know" solution to delete this folder, closing
