### ISSUE TITLE
Feature Request: Add compass in setup screen

### ISSUE THREAD

**Issue by davidngrc** [iNavFlight/inav-configurator#485]
I have a BN-880 GPS, it has a build in compass, in iNav configurator, I have no idea knowing I am putting the compass on the right-side up or not.

If in setup screen, it shows a compass graphic, I then simply moving the compass from left to right, then I will know if I am putting the compass right, or I need to change the "MAG Alignment" or not.

BTW 1, if I change the "MAG Alignment", the compass in the setup screen need to change accordingly.
otherwise, I had no idea if the changed "MAG Alignment" value is correct or not.

BTW 2, if I set the compass wrong, like up side down, what will happen?
it has an arrow pointing one way in this picture https://img.staticbg.com/thumb/water/upload/2015/05/SKU206532.jpg
and we have many option in "MAG Alignment"
I mean a physical compass,  no matter which orientation you put in it, it always point north.
Can't the digit compass do that?
Why do we need to set "MAG Alignment"?

**Comment by digitalentity** [comment]
>If in setup screen, it shows a compass graphic, I then simply moving the compass from left to right, then I will know if I am putting the compass right, or I need to change the "MAG Alignment" or not.

Heading value is precisely the direction of the front part of the aircraft relative to North as seen by flight controller.

>BTW 1, if I change the "MAG Alignment", the compass in the setup screen need to change accordingly.

You need to set it to correct value so that North equals Heading of 0 deg, East - 90, West - 270, South - 180 and the value doesn't change when you roll/pitch the aircraft.

>BTW 2, if I set the compass wrong, like up side down, what will happen?

Heading will drift when you tilt the aircraft.

>I mean a physical compass, no matter which orientation you put in it, it always point north. Can't the digit compass do that?

The magnetometer sensor measures magnetic field in 3D space and the chip itself knows exactly where the (magnetic) North is and exposes it as a direction which is **relative to chip itself**. The flight controller has no idea how this compass is oriented and thus in which direction aircraft is heading.

In your example with a physical compass. Imagine looking at the compass while sitting in a closed box inside aircraft. Knowing where North is won't help you if you don't know which direction is "forward" of the aircraft. This difference between aircraft "forward" and compass "north" is mag alignment.

Regarding the setup itself - RTM here https://github.com/iNavFlight/inav/wiki/Sensor-calibration#verifying-that-compass-is-calibrated-properly
