### ISSUE TITLE
motor direction switch in GUI 2.1.4 missing !!!

### ISSUE THREAD

**Issue by yo8aiv** [iNavFlight/inav-configurator#793]
as title says motor direction switch in GUI is missing 
the interface is supposed to make life easyer right. 

same thing i have seen missing in latest BF GUI interface app aswell. 
 its annoying because when i fly low all the grass get's thrown as a salad in the camera lens so i prefer reversing motor rotation to avoid it.
![BFmotor_direction](https://user-images.githubusercontent.com/24196117/59229319-52375480-8bda-11e9-85bc-51e306f618ef.jpg)

meaning i prefer having a graphical representation of how motor direction is set in the FC. 
if this has been submitted just close the issue.
thanks.

**Comment by Mateyhv** [comment]
Yes, it will be a nice implementation since even if you reverse the motion in ESC and Inav mixer, the arrows still point giving a wrong information to the user. Meanwhile you can do the modification to the ESC via BlHeli or changing two of the three cables to the motor to reverse motor direction and then change the sign of YAW for all four motors in the mixer because of the reversed torque.
