### ISSUE TITLE
[Linux] Application-Window not resizable

### ISSUE THREAD

**Issue by Neuroplant** [iNavFlight/inav-configurator#884]
Application-Window is too big for my Notebook.Screen (1368x768) and not resizeable.
So I can not use it, buttons on bottom not reachable
(OS:Ubuntu 18.04.3 LTS Desktop)
Hope you can fix this
Neuroplant

**Comment by stopdick** [comment]
Same thing here! It appears that the minimum size for the inav configurator window is "1024x800". Running it on my notebook which has a 13.3in (1366x768) screen hides the bottom of the window. Its pretty important because i can not see and use the "Save" button. I also don't get the option to maximize the window.

A work around is to move the window up by pressing the "Alt+F7" keys and move the mouse (or hold "Alt"+Click the window and then move it, depending the system you are using).

![screen sizes](https://user-images.githubusercontent.com/22023523/71575642-6307d300-2af6-11ea-8aab-dbcb0cf7c877.png)

**Comment by rsilk1949** [comment]
Same problem on WIndows 10 laptop with screen 1366x768

**Comment by rsilk1949** [comment]
> Same problem on WIndows 10 laptop with screen 1366x768.
Can be "fixed" by maximising window each time I open the app.

**Comment by Neuroplant** [comment]
@rsilk1949 this is not the same problem as the window IS resizeable under Win10.
It is just a little inconvinient

**Comment by DzikuVx** [comment]
#942 min windows size was lowered to 800x600
